Blueqat/Blueqat

tests/test_vqe.py
use pytest decorator to parametalize test case
=> refactor test using decorator

tutorial/012_algo_teleportation.ipynb
this PR fixes a dead link in tutorial.
=> deadline in tutorial

blueqat/backends/qgate_backend.py, blueqat/circuit.py, examples/qaoa_via_qgate.py
2 new files:
blueqat/backends/qgate_backend.py : The first version of qgate backend.
blueqat/examples/qaoa_via_qgate.py : An example to show qgate backend usage.
1 patch:
blueqat/circuit.py : qgate is added to the backend table.
=> Qgate plugin

.circleci/config.yml, blueqat/backends/_numba_backend_impl.py, tests/test_circuit.py
=> [numba backend] Fix error of multi-qubit gate failure

.circleci/config.yml, blueqat/backends/_numba_backend_impl.py, tests/test_circuit.py
Process of making bit mask has several bugs.
Correct them and add tests of simple CX circuit and complicated circuit also.
=> Numba debug3

blueqat/backends/sympy_backend.py, blueqat/circuit.py, blueqat/gate.py, tests/test_circuit.py, tests/test_sympy.py
Add controlled H gate and controlled Y gate and test for them.
close #55
=> ENH: Add controlled-H and controlled-Y gate

blueqat/circuit.py, blueqat/gate.py
Implement `__repr__` method for Circuit class
=> Implement Circuit.__repr__

blueqat/backends/_numba_backend_impl.py, blueqat/backends/numpy_backend.py, blueqat/backends/qgate_backend.py, tests/test_circuit.py
Global phase adjustment is done.
=> Global phase adjustment and numba debug

blueqat/experimental/__init__.py, blueqat/experimental/operations.py
Experimental module contains experimental & unstable feature and implementation.
=> Experimental module

.circleci/config.yml, blueqat/backends/qgate_backend.py, tests/test_circuit.py
Correct test and remove qgate adhoc because qgate bug was solved
=> Correct test and remove qgate adhoc because qgate bug was solved

blueqat/circuit.py, blueqat/experimental/operations.py, blueqat/gate.py, tests/test_dagger.py
Enhancement for add Circuit.dagger, it makes Hermitian conjugate of the circuit.
=> Enhancement for add Circuit.dagger, it makes Hermitian conjugate of the circuit.

blueqat/experimental/utils.py
Add experimental utility code and `circuit_to_unitary` function.
=> EXP: Add experimental.utils and circuit_to_unitary 

blueqat/pauli.py, tests/test_pauli.py
- Refactoring `pauli.to_matrix()`
- Add sparse matrix support
=> Improve pauli to matrix

blueqat/vqe.py
Add mixer for QaoaAnsatz. This is required for Quantum Alternative Operator Ansatz.
This feature is experimental. Specification may be changed.
=> ENH: Add mixer for QaoaAnsatz

blueqat/vqe.py
In Vqe class, when sampler is None, make sparse matrix and calculate expectation directly.
VQE is still under refactoring process and this API may be changed in future release, however, because this feature is very important, I want to merge this feature in the master.
=> ENH: Implement sparse matrix expectation for VQE

blueqat/_version.py, blueqat/pauli.py, tests/test_pauli.py
=> Sparse hotfix

blueqat/pauli.py, tests/test_pauli.py
- Improve performance for Term.to_matrix and Expr.to_matrix.
- Debug Term.simplify()
- Add Term.n_qubits, Expr.n_qubits property
=> Fast tomatrix

blueqat/backends/_numba_backend_impl.py, tests/test_circuit.py
Correct wrong global phase for numba implementation.
=> BUG: Correct numba global phase

.circleci/config.yml, blueqat/backends/_numba_backend_impl.py, optional-requirements.txt, tests/test_circuit.py
Update Python and Numba version.
Now, test for numba backend is work well. This PR fixes #81.
=> Circle CI config update

blueqat/backends/__init__.py, blueqat/backends/_numba_backend_impl.py, blueqat/backends/ibmq_backend.py, blueqat/backends/manyqubitgate_fallbacker.py, blueqat/backends/numpy_backend.py, blueqat/backends/onequbitgate_decomposer.py, blueqat/backends/onequbitgate_transpiler.py, blueqat/backends/twoqubitgate_transpiler.py, blueqat/circuit.py, blueqat/gate.py, blueqat/utils.py, tests/test_circuit.py
Add mat1 gate, ZZ gate, gate decompositor and refactoring
=> Add mat1 gate, ZZ gate, gate decompositor and refactoring

blueqat/backends/qgate_backend.py, examples/qaoa_via_qgate.py
Modifications for qgate 0.4 (Thank you, Morino-san!!)
=> For qgate 0.4

blueqat/backends/qgate_backend.py, tests/test_circuit.py
SWAP gate occurs error in qgate backend . Now, it's corrected.
=> BUG: Debug qgate backend for multi qubit gate

.circleci/config.yml, blueqat/backends/_numba_backend_impl.py, blueqat/backends/backendbase.py, blueqat/backends/ibmq_backend.py, blueqat/backends/manyqubitgate_fallbacker.py, blueqat/backends/numpy_backend.py, blueqat/backends/onequbitgate_transpiler.py, blueqat/backends/qasm_output_backend.py, blueqat/backends/qasm_parser_backend_generator.py, blueqat/backends/qgate_backend.py, blueqat/backends/sympy_backend.py, blueqat/backends/twoqubitgate_transpiler.py, blueqat/circuit.py, blueqat/experimental/operations.py, blueqat/experimental/utils.py, blueqat/gate.py, blueqat/pauli.py, blueqat/utils.py, blueqat/vqe.py, blueqat/wq.py
Cache is default disabled in numpy and numba backend, but have context cache for effective running, it is discarded after run.
=> Cache default disabled

blueqat/backends/_numba_backend_impl.py, blueqat/backends/numpy_backend.py, tests/test_circuit.py, tests/test_sympy.py
```py
vec = Circuit(2).x[0].run()
count = Circuit().x[1].m[:].run(initial=vec, shots=100)
```
=> Add initial statevector input option to numpy and numba backend

blueqat/backends/qgate_backend.py, tests/test_circuit.py
=> ENH: Enable initial vector in qgate backend

.circleci/config.yml, optional-requirements.txt
Add Python 3.9 to test workflow.
=> TST: Add 3.9 test

blueqat/gate.py
Add CU gate fallback by CX gate. It is convenient for non-simulator instance.
=> Add CU gate fallback

blueqat/wq.py
comparisons to the singleton objects, like True, False, and None should be done with identity, not equality
=> Comparison to singleton True should be expr "is"

blueqat/circuit.py, tests/test_circuit.py
Add `Circuit.statevector()`, `Circuit.shots()`, `Circuit.oneshot()`.
Close #115
=> Well-typed running

blueqat/circuit_funcs/__init__.py, blueqat/circuit_funcs/flatten.py, blueqat/circuit_funcs/json_serializer.py, tests/test_json.py
Implemented JSON serializer/deserializer.
=> Json serializer/deserializer

blueqat/backends/onequbitgate_decomposer.py, blueqat/circuit_funcs/__init__.py, blueqat/circuit_funcs/circuit_to_unitary.py, blueqat/macros/__init__.py, blueqat/utils.py, tests/test_macros.py
- Implement built-in macros.
- Move circuit_to_unitary function utils to circuit_utils.
=> Builtin macros

blueqat/backends/numpy_backend.py, blueqat/circuit.py, blueqat/circuit_funcs/flatten.py, blueqat/circuit_funcs/json_serializer.py, blueqat/gate.py, blueqat/gateset.py, tests/test_1qdecompose.py, tests/test_json.py, tests/test_measurekey.py
Experimental feature for sampling to classical register.
=> samples feature

blueqat/gate.py
=> BUG: Correct TGate.matrix() and TDagGate.matrix(), IGate.matrix()

README.md, blueqat/_version.py, blueqat/photonqat/Fock.py, blueqat/photonqat/Fockbase/WignerFunc.py, blueqat/photonqat/Fockbase/__init__.py, blueqat/photonqat/Fockbase/bosonicLadder.py, blueqat/photonqat/Fockbase/gateOps.py, blueqat/photonqat/Fockbase/gates.py, blueqat/photonqat/Fockbase/stateOps.py, blueqat/photonqat/Fockbase/states.py, blueqat/photonqat/Gaussian.py, blueqat/photonqat/Gaussianformula/__init__.py, blueqat/photonqat/Gaussianformula/baseFunc.py, blueqat/photonqat/Gaussianformula/gateOps.py, blueqat/photonqat/Gaussianformula/gates.py, blueqat/photonqat/Gaussianformula/ordering.py, blueqat/photonqat/__init__.py, blueqat/photonqat/opt.py, examples_photonqat/Basic Operations.ipynb, examples_photonqat/GaussianGates.ipynb, examples_photonqat/KerrGate.ipynb, examples_photonqat/PhotonCountingForGaussian.ipynb, examples_photonqat/StateTeleportation.ipynb, examples_photonqat/catState.ipynb, examples_photonqat/photonqat_Fock.ipynb, setup.py
Photonic continuous variable programming photonqat integrated
=> Photonqat Integrated

README.md
=> Blueqat.blueqat.utils-->blueqat.utils

blueqat/__init__.py, blueqat/gate.py, blueqat/parameter.py, blueqat/parametrized_circuit.py, blueqat/typing.py, tests/test_parametrized_circuit.py
I added ParametrizedCircuit class.
Usage:
```py
from blueqat import Circuit, ParametrizedCircuit
def compare_circuit(c1: Circuit, c2: Circuit) -> bool:
return repr(c1) == repr(c2)
def test_parametrized1():
assert compare_circuit(
ParametrizedCircuit().ry('a')[0].rz('b')[0].subs([1.2, 3.4]),
Circuit().ry(1.2)[0].rz(3.4)[0])
def test_parametrized2():
assert compare_circuit(
ParametrizedCircuit().ry('a')[0].rz('b')[0].subs({'a': 1.2, 'b': 3.4}),
Circuit().ry(1.2)[0].rz(3.4)[0])
```
=> ENH: Add ParametrizedCircuit

blueqat/backends/__init__.py
fix import error for cuquantum backend.
=> fix import error

blueqat/__init__.py, blueqat/gate.py, blueqat/parameter.py, blueqat/parametrized_circuit.py, blueqat/typing.py, tests/test_parametrized_circuit.py
Change typing for python<=3.8.
=> Parametrized circuit
